#! /usr/bin/ruby

require 'fileutils'

DEFAULT_PROJECT_PATH = '/Users/gaofei/Projects/jssanguo/frameworks/runtime-src/proj.ios_mac/jssanguo.xcodeproj'
TARGET_DIR_PATH = "/Users/gaofei/Desktop/Vietnam/Archives"
LAST_BUILD_PATH = "/Users/gaofei/Desktop/Vietnam/Archives_lastbuild"

def check_directory
	FileUtils.mkdir_p(TARGET_DIR_PATH) if not File.exist?(TARGET_DIR_PATH)
	FileUtils.mkdir_p(LAST_BUILD_PATH) if not File.exist?(LAST_BUILD_PATH)
end

def check_file(filename)
	FileUtils.mv("#{TARGET_DIR_PATH}/#{filename}", "#{LAST_BUILD_PATH}/#{filename}") if File.exist?("#{TARGET_DIR_PATH}/#{filename}")
end

def archive_target(target_name)
	target_file = "#{target_name}.xcarchive"
	check_directory
	check_file target_file

	command_str = "xcodebuild archive -project '#{DEFAULT_PROJECT_PATH}' "
	command_str += "-sdk 'iphoneos8.4' "
	command_str += "-scheme '#{target_name}' "
	command_str += "-archivePath '#{TARGET_DIR_PATH}/#{target_file}' "

	# puts "Cyan (36)"
	puts "Run: \033[35m#{command_str}\033[0m"
	system command_str
end

def export_IPA(target_name)
	target_file = "#{target_name}.ipa"
	check_directory
	check_file target_file

	archive_path = "#{TARGET_DIR_PATH}/#{target_name}.xcarchive"
	ipa_path = "#{TARGET_DIR_PATH}/#{target_name}.ipa"

	if not File.exist?(archive_path)
		puts "\033[31mError: \033[0m" + "\033[36m#{archive_path}\33[0m not exist."
		return
	end

	command_str = "xcodebuild -exportArchive -exportFormat IPA -archivePath '#{archive_path}' -exportPath '#{ipa_path}'"
	puts "Excuting: \033[35m#{command_str}\033[0m"
	system command_str
end

def main()
	puts "Choose Target:"
	puts "[1] PK to App Store"
	puts "[2] PK to Enterprise"
	puts "[3] Export 'PK to App Store' to IPA"
	puts "[4] Export 'PK to Enterprise' to IPA"

	select_id = gets.to_i

	if [1, 2, 3, 4].include?(select_id)
		case select_id
		when 1
			archive_target 'PK to App Store'
		when 2
			archive_target 'PK to Enterprise'
		when 3
			export_IPA 'PK to App Store'
		when 4
			export_IPA 'PK to Enterprise'
		end	
	else
		puts "\033[31mError: \033[0m" + "Invalid Target: #{select_id}"
	end
end




# Real excution
main
