#! /usr/bin/ruby

require 'pathname'
require 'fileutils'

TEMPLATE_FILE = Pathname.new('/Users/gaofei/Scripts/A/template_project_name.sesx')

name = ARGV[0]
directory = Pathname.new(ARGV[1] || '.')

TIP = "create_sound_project [NAME] [DIRECTORY]"

def print_error(message)
	# puts ""
	puts "😡 😡 😡 !!! #{message}"
	# puts ""
end

def create_project(fullpath, content)
	File.open(fullpath, 'w') do |file|
		file.write(content)
	end
end

puts ""
puts "[Start] >>>>>>>>>>>>>>>>>>"
puts ""
begin
	# Check template file...
	if not TEMPLATE_FILE.exist?
		error_msg = "Something wrong with template file. Check it out."
		print_error(error_msg)
		break;
	end

	# Check name...
	if name.nil? or name.empty?
		error_msg = "Should specify a NAME for project. - Format: #{TIP}"
		print_error(error_msg)
		break;
	end

	# Check directory...
	if not directory.exist?
		error_msg = "The directory: '#{directory}' NOT exist, check it again."
		print_error(error_msg)
		break;
	end

	projects = [
		"#{name}_attack",
		"#{name}_skill1",
		"#{name}_skill2",
		"#{name}_combine_skill"
	]

	# Create project directory.
	project_direcotry = directory.realpath + name
	if project_direcotry.exist?
		puts "[/] 👀  SKIP: '#{project_direcotry.realpath}' already exists."
	else
		FileUtils::mkdir_p(project_direcotry)
		puts "[+] 😚  Creating directory: '#{project_direcotry.realpath}'"
	end

	# Create project file.

	template_content = File.open(TEMPLATE_FILE, 'r') {|file| file.read}
	projects.each do |project_name|
		filepath = project_direcotry + "#{project_name}.sesx"
		if filepath.exist?
			puts "[/] 👀  SKIP: '#{filepath.realpath}' already exists."
		else
			File.open(filepath, 'w') {|file| file.write(template_content.gsub('template_project_name', project_name))}
			puts "[+] 😚  Creating project '#{filepath.realpath}'"
		end
	end

	# Create 'Conformed Files' directory.
	cf_dir = project_direcotry + 'Conformed Files'
	if cf_dir.exist?
		puts "[/] 👀  SKIP: '#{cf_dir.realpath}' already exists."
	else
		FileUtils::mkdir_p(cf_dir)
		puts "[+} 😚  Creating directory '#{cf_dir.realpath}'"
	end
end while false

puts ""
puts "<<<<<<<<<<<<<<<<<< [Done]"
puts ""