#! /usr/bin/ruby

require 'fileutils'
require 'pathname'

SRC_DIR = Pathname.new('/Users/gaofei/360云盘/三国/程序/配置文件UTF8')
# SRC_DIR = Pathname.new('/Users/gaofei/Desktop/sanguo/程序/配置文件UTF8')
PRJ_DIR = Pathname.new('/Users/gaofei/Projects/jssanguo/res/config')

destination_files = Dir[PRJ_DIR + '*.csv']

destination_files.each do |file|
	pn = Pathname.new(file)
	filename = pn.basename
	src_file = SRC_DIR + filename
	if src_file.exist?
		FileUtils.cp(SRC_DIR + filename, PRJ_DIR)
		puts "😚  OK: [#{filename}]"
	else
		puts ""
		puts "💢 💢 💢   Error: [#{src_file}] not exist!  😡 😡 😡"
		puts ""
	end
	
end
